name = "grovetools"
workspaces = ["*"]

[llm]
default_model = "gemini-3-pro-preview"

[skills]
use = ["grove-skill-builder", "grove-skill-maintainer", "grove-feature-coordinator", "grove-concept-maintainer", "concept-scoped-planner", "flow-context-tuner", "grove-feature-coordinator-v2", "grove-feature-subcoordinator"]
